# Variables needed for this file.
# Commented out values are passed from the parent pipeline.
variables:
  # Logger tag value.
  #SF_TARGET_ARCH: "amd64"
  #SF_TARGET_OS: "linux"
  # Directory for generated packages.
  #SF_DIR_PKG: "bin/pkg"
  # CMake toolchain the preset-name with.
  #SF_TOOLCHAIN: "gnu"
  # CMake build type to construct the preset-name with.
  #SF_BUILD_TYPE: "debug"
  # Output directory relative to the working directory.
  #SF_DIR_BIN: "bin/lnx64"
  # Name of the branch that allows running deploying to production.
  #SF_RELEASE_BRANCH: "main"
  # Fixed base directory the source root is mounted to between jobs for each toolchain.
  SF_DIR_MOUNT: "/tmp/binder/${CI_COMMIT_SHORT_SHA}-${SF_TOOLCHAIN}"
  # Make Git clone the submodules as well.
  GIT_SUBMODULE_STRATEGY: recursive

# Required for trigger pipelines so run always.
workflow:
  rules:
    - when: always
  # Cancel when there is a new commit.
  auto_cancel:
    on_new_commit: interruptible

# Order of stages for jobs to perform in.
stages:
  # Jobs checking the environment requirements.
  - check
  # Jobs producing makefiles using CMake presets.
  - configure
  # Jobs for building all cmake preset targets.
  - build
  # Jobs executing the build unittests using the CTest configurations.
  - test
  # Jobs packing the generated artifacts.
  - pack
  # Deploy generated packages.
  - deploy

# Template to dump all environment variables.
.env-dump:
  # Do not need the cache for this one.
  cache: []
  before_script:
    - echo "Working Directory=$(pwd)" && echo "Environment Dump" && printenv | sort
  script:
    - echo "..."

# Fetches tags and checks if a tag describes current state of the repository.
# Is not, unshallow is tried and exits when no tag is still not found.
.script-tags: &tags-script
  - |
    # Prevent error when fetching.
    git config --global --add safe.directory '*'
    # Fetch all the tags
    git fetch --tags --force
    # List the tags so the wind up in the log.
    git tag --list
    # When not able to describe GitLab is cloning too shallow.
    if ! git describe --dirty; then
      echo "Could not find tag describing this repo. Trying git unshallow..."
      git fetch --unshallow
      # Checking again.
      if ! git describe --dirty; then
        echo "Could not git describe and is probably missing a version tag!"
        exit 1
      fi
    fi    

# Script to mount source root on a fixed directory path for cmake.
.script-bind: &bind-script
  - mkdir -p "${SF_DIR_MOUNT}" && ! mountpoint "${SF_DIR_MOUNT}" && bindfs "${PWD}" "${SF_DIR_MOUNT}" || exit 1

# Template to unmount source root on a fixed directory path for cmake.
.script-unbind: &unbind-script
  - mountpoint "${SF_DIR_MOUNT}" && fusermount -uz "${SF_DIR_MOUNT}" && rmdir "${SF_DIR_MOUNT}" || exit 1

# Template to configure cache for CMake generated files for the compiler.
.cache:
  cache:
    key: "${CI_COMMIT_REF_NAME}.${CI_COMMIT_SHORT_SHA}-${SF_TOOLCHAIN}"
    paths:
      - "cmake-build/*"
    policy: pull-push

# Template to define artifacts in the designated directory.
.artifacts-build:
  artifacts:
    name: "${CI_COMMIT_REF_NAME}-${SF_TOOLCHAIN}-binaries"
    # Expiration period before artifacts expire.
    # FIXME: Currently variable expansion is not possible and is fixed.
    # (See: https://gitlab.com/gitlab-org/gitlab/-/issues/365855)
    expire_in: 2 days
    paths:
      - "${SF_DIR_BIN}/"
    exclude:
      - "**/.gitkeep"

# Template to define package generated artifacts in the designated directory.
.artifacts-pack:
  artifacts:
    name: "${CI_COMMIT_REF_NAME}-${SF_TOOLCHAIN}-packages"
    expire_in: 7 days
    paths:
      # Package generator DEB Debian results.
      - "${SF_DIR_PKG}/*.deb"
      # Package generator RPM results.
      - "${SF_DIR_PKG}/*.rpm"
      # Package generator NSIS and NSIS64 results.
      - "${SF_DIR_PKG}/*.exe"
      # Package generator ZIP results.
      - "${SF_DIR_PKG}/*.zip"
    exclude:
      - "**/.gitkeep"

# Defaults for all jobs.
default:
  # Set a specific Docker image to execute all jobs in.
  image: "${SF_DOCKER_IMAGE}"
  # Tags determine the selection of a runner.
  tags:
    - cplusplus
    - "${SF_TARGET_OS}"
    - "${SF_TARGET_ARCH}"
  # Allow to be interrupted.
  interruptible: true

# Obligatory in this setup of jobs depending on or needs it.
# Reports the environment variables set for the all jobs.
job-check:
  # Common template job.
  extends: .env-dump
  stage: check
  script:
    - echo "..."

# Job for creating the make-file using the build.sh script calling CMake with appropriate arguments.
# Wiping build directory is not needed since the push policy.
job-config:
  stage: configure
  needs:
    - job: job-check
  extends: [.cache]
  cache:
    policy: push
  script:
    - *bind-script
    # The make stage needs tags for versioning of shared libraries and packaging.
    - *tags-script
    # Execute the build script to CMake the makefiles.
    - '"${SF_DIR_MOUNT}/build.sh" --make "${SF_TOOLCHAIN}-${SF_BUILD_TYPE}"'
    - *unbind-script

job-build:
  stage: build
  needs:
    - job: job-config
  extends: [.cache, .artifacts-build]
  cache:
    policy: pull
  script:
    - *tags-script
    - *bind-script
    # Execute the build script to actually build the running target and libraries.
    - '"${SF_DIR_MOUNT}/build.sh" --build-only "${SF_TOOLCHAIN}-${SF_BUILD_TYPE}"'
    - *unbind-script

job-test:
  stage: test
  extends: [.cache]
  needs:
    - job: job-build
  cache:
    policy: pull
  script:
    - *bind-script
    # Run the test which in Linux can have absolute path dependencies to dynamic libraries.
    - '"${SF_DIR_MOUNT}/build.sh" --test "${SF_TOOLCHAIN}-${SF_BUILD_TYPE}"'
    - *unbind-script

job-pack:
  stage: pack
  extends: [.cache, .artifacts-pack]
  needs:
    - job: job-build
  cache:
    policy: pull
  script:
    - *bind-script
    # Build the 'install' target which enables cpack to pick them up.
    - '"${SF_DIR_MOUNT}/build.sh" --build-only "${SF_TOOLCHAIN}-${SF_BUILD_TYPE}" --target install'
    - '"${SF_DIR_MOUNT}/build.sh" --package "${SF_TOOLCHAIN}-${SF_BUILD_TYPE}" '
    - *unbind-script

# Template for all deploy jobs.
.deploy:
  needs:
    - job: job-pack
    - job: job-test
  script:
    # Upload all generated packages to Nexus depending on their extension to a specific destination.
    - 'find "${SF_DIR_PKG}" -maxdepth 1 -type f -name "*.deb" -o -name "*.exe" -o -name "*.zip" | xargs cmake/lib/bin/upload-nexus.sh'

# Use non specific environment depended variables.
job-deploy-develop:
  stage: deploy
  extends:
    - .deploy
  rules:
    # For testing the 'deploy' step in any scenario.
    - if: '$SF_SIGNAL == "deploy"'
      when: manual
      # Make this job optional.
      allow_failure: true
    # Skip when this is the configured release branch.
    - if: '$CI_COMMIT_BRANCH == $SF_RELEASE_BRANCH'
      when: never
    # Develop is allowed to automatically deploy.
    - when: always

# Use variables set using environment 'stable'.
job-deploy-staging:
  stage: deploy
  extends:
    - .deploy
  environment: staging
  rules:
    # For testing the 'deploy' step in any scenario.
    - if: '$SF_SIGNAL == "deploy"'
      when: manual
      # Make this job optional.
      allow_failure: true
    # When this branch is not the release branch set it allow manual deployment.
    - if: '$CI_COMMIT_REF_NAME == $SF_RELEASE_BRANCH'
      when: manual
      allow_failure: true
    # Staging is allowed to automatically deploy.
    - when: always

# Use variables set using environment 'stable'.
job-deploy-stable:
  stage: deploy
  extends:
    - .deploy
  environment: stable
  rules:
    # For testing the 'deploy' step in any scenario.
    - if: '$SF_SIGNAL == "deploy"'
      when: manual
      # Make this job optional.
      allow_failure: true
    # Skip when this is not the configured release branch.
    - if: '$CI_COMMIT_BRANCH == $SF_RELEASE_BRANCH'
      when: manual
      # Make this job optional.
      allow_failure: true
    # Never by deploy a release.
    - when: never
