# See: https://cmake.org/cmake/help/latest/cpack_gen/nsis.html
set(CPACK_NSIS_MUI_ICON "${CMAKE_CURRENT_LIST_DIR}/../doc/logo.ico")
set(CPACK_NSIS_MUI_UNIICON "${CMAKE_CURRENT_LIST_DIR}/../doc/logo.ico")
set(CPACK_NSIS_PACKAGE_NAME "${CMAKE_PROJECT_NAME} ${CPACK_PACKAGE_VERSION}")
set(CPACK_NSIS_DISPLAY_NAME "${CMAKE_PROJECT_NAME}")
set(CPACK_NSIS_URL_INFO_ABOUT "${CMAKE_PROJECT_HOMEPAGE_URL}")
set(CPACK_NSIS_HELP_LINK "${CMAKE_PROJECT_HOMEPAGE_URL}")
set(CPACK_NSIS_CONTACT "Arjan van Olphen <a.v.olphen@scanframe.nl>")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
set(CPACK_NSIS_IGNORE_LICENSE_PAGE ON)




